---@module Unit Load Lookup
local M = {
	{
		unit_included = "units/payday2/characters/ene_cop_1/ene_cop_1",
		units_to_load = {
			{ path = "units/payday2/characters/ene_cop_1_fat/ene_cop_1_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_cop_2_fat/ene_cop_2_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_cop_3_fat/ene_cop_3_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_cop_4_fat/ene_cop_4_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_cop_female_1/ene_cop_female_1", load_husk = true },
			{ path = "units/payday2/characters/ene_cop_female_2/ene_cop_female_2", load_husk = true },
		},
	},
	{
		unit_included = "units/payday2/characters/ene_security_1/ene_security_1",
		units_to_load = {
			{ path = "units/payday2/characters/ene_security_1_fat/ene_security_1_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_security_2_fat/ene_security_2_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_security_3_fat/ene_security_3_fat", load_husk = true },
			{ path = "units/payday2/characters/ene_security_female_1/ene_security_female_1", load_husk = true },
			{ path = "units/payday2/characters/ene_security_female_2/ene_security_female_2", load_husk = true },
		},
	},
	{
		unit_included = "units/payday2/characters/ene_swat_1/ene_swat_1",
		units_to_load = {
			{ path = "units/payday2/characters/ene_acc_swat_cap/ene_acc_swat_cap", load_husk = false },
			{ path = "units/payday2/characters/ene_acc_swat_heavy_visor/ene_acc_swat_heavy_visor", load_husk = false },
			{ path = "units/payday2/characters/ene_acc_city_swat_cap/ene_acc_city_swat_cap", load_husk = false },
			{ path = "units/payday2/characters/ene_swat_3/ene_swat_3", load_husk = true },
			{ path = "units/payday2/characters/ene_tazer_r870/ene_tazer_r870", load_husk = true },
			{ path = "units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3", load_husk = true },
			{ path = "units/payday2/characters/ene_sniper_3/ene_sniper_3", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc1/characters/ene_security_gensec_1/ene_security_gensec_1",
		units_to_load = {
			{ path = "units/pd2_dlc1/characters/ene_security_gensec_1/ene_security_gensec_1", load_husk = false },
			{ path = "units/pd2_dlc1/characters/ene_gensec_operator_1/ene_gensec_operator_1", load_husk = true },
			{ path = "units/pd2_dlc1/characters/ene_gensec_operator_2/ene_gensec_operator_2", load_husk = true },
		},
	},
	{
		unit_included = "units/payday2/characters/ene_bulldozer_4/ene_bulldozer_4",
		units_to_load = {
			{ path = "units/payday2/characters/ene_bulldozer_5/ene_bulldozer_5", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
		units_to_load = {
			{ path = "units/pd2_dlc_drm/characters/ene_bulldozer_medic_classic/ene_bulldozer_medic_classic", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_mad/weapons/wpn_npc_ak47/wpn_npc_ak47",
		units_to_load = {
			{ path = "units/pd2_dlc_mad/weapons/wpn_npc_rpk_bulldozer/wpn_npc_rpk_bulldozer", load_husk = false },
			{ path = "units/pd2_dlc_mad/weapons/wpn_npc_vityaz/wpn_npc_vityaz", load_husk = false },
			{ path = "units/pd2_dlc_mad/weapons/wpn_npc_pl14_tactical/wpn_npc_pl14_tactical", load_husk = false },
			{ path = "units/pd2_dlc_mad/weapons/wpn_npc_ak47_elite/wpn_npc_ak47_elite", load_husk = false },
			{ path = "units/pd2_dlc_mad/weapons/wpn_npc_svd_dmr/wpn_npc_svd_dmr", load_husk = false },
		},
	},
	{
		unit_included = "units/pd2_dlc_mad/characters/ene_akan_cs_swat_ak47_ass/ene_akan_cs_swat_ak47_ass",
		units_to_load = {
			{ path = "units/pd2_dlc_mad/characters/ene_acc_cop_hat/ene_acc_cop_hat", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_fbi_cap/ene_acc_fbi_cap", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_swat_helmet/ene_acc_swat_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_swat_hat/ene_acc_swat_hat", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_fbi_swat_helmet/ene_acc_fbi_swat_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_city_swat_helmet/ene_acc_city_swat_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_city_swat_hat/ene_acc_city_swat_hat", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_swat_heavy_helmet/ene_acc_swat_heavy_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_city_heavy_helmet/ene_acc_city_heavy_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_swat_heavy_visor/ene_acc_swat_heavy_visor", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_shield_mask/ene_acc_shield_mask", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_medic_helmet/ene_acc_medic_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_tazer_helmet/ene_acc_tazer_helmet", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_tazer_mask/ene_acc_tazer_mask", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_shield_akan_small/ene_acc_shield_akan_small", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_shield_akan_shield/ene_acc_shield_akan", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_shield_city/ene_acc_shield_city", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_acc_shield_city/ene_acc_shield_city_dummy", load_husk = false },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_cs_cop_c45/ene_akan_cs_cop_c45", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_cs_cop_raging_bull/ene_akan_cs_cop_raging_bull", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_agent_c45/ene_akan_fbi_agent_c45", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_agent_ak47_ass/ene_akan_fbi_agent_ak47_ass", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_agent_akmsu_smg/ene_akan_fbi_agent_akmsu_smg", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_cs_swat_akmsu_smg/ene_akan_cs_swat_akmsu_smg", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_swat_akmsu_smg/ene_akan_fbi_swat_akmsu_smg", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_swat_sniper_svd_snp/ene_akan_fbi_swat_sniper_svd_snp", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_swat_ak47_ass/ene_akan_city_swat_ak47_ass", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_swat_r870/ene_akan_city_swat_r870", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_swat_akmsu_smg/ene_akan_city_swat_akmsu_smg", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_swat_sniper_svd_dmr/ene_akan_city_swat_sniper_svd_dmr", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_shield/ene_akan_city_shield", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_heavy_g36/ene_akan_city_heavy_g36", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_city_heavy_r870/ene_akan_city_heavy_r870", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_cs_tazer_r870/ene_akan_cs_tazer_r870", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_tank_mini/ene_akan_fbi_tank_mini", load_husk = true },
			{ path = "units/pd2_dlc_mad/characters/ene_akan_fbi_tank_medic/ene_akan_fbi_tank_medic", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_hvh/characters/ene_cop_hvh_1/ene_cop_hvh_1",
		units_to_load = {
			{ path = "units/pd2_dlc_hvh/characters/ene_swat_hvh_3/ene_swat_hvh_3", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_sniper_hvh_1/ene_sniper_hvh_1", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_fbi_swat_hvh_3/ene_fbi_swat_hvh_3", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_city_swat_hvh_1/ene_city_swat_hvh_1", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_city_swat_hvh_2/ene_city_swat_hvh_2", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_city_swat_hvh_3/ene_city_swat_hvh_3", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_sniper_hvh_3/ene_sniper_hvh_3", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_city_shield_hvh/ene_city_shield_hvh", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_city_heavy_hvh_1/ene_city_heavy_hvh_1", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_city_heavy_hvh_r870/ene_city_heavy_hvh_r870", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_tazer_hvh_r870/ene_tazer_hvh_r870", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_bulldozer_hvh_4/ene_bulldozer_hvh_4", load_husk = true },
			{ path = "units/pd2_dlc_hvh/characters/ene_bulldozer_medic_hvh/ene_bulldozer_medic_hvh", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_rvd/characters/ene_la_cop_1/ene_la_cop_1",
		units_to_load = {
			{ path = "units/pd2_dlc_rvd/characters/ene_la_cop_1_fat/ene_la_cop_1_fat", load_husk = true },
			{ path = "units/pd2_dlc_rvd/characters/ene_la_cop_2_fat/ene_la_cop_2_fat", load_husk = true },
			{ path = "units/pd2_dlc_rvd/characters/ene_la_cop_3_fat/ene_la_cop_3_fat", load_husk = true },
			{ path = "units/pd2_dlc_rvd/characters/ene_la_cop_4_fat/ene_la_cop_4_fat", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_bph/characters/ene_murkywater_light/ene_murkywater_light",
		units_to_load = {
			{ path = "units/pd2_dlc_bph/characters/ene_acc_cop_hat/ene_acc_cop_hat", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_fbi_cap/ene_acc_fbi_cap", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_security_cap/ene_acc_security_cap", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_swat_helmet/ene_acc_swat_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_swat_hat/ene_acc_swat_hat", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_fbi_swat_helmet/ene_acc_fbi_swat_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_city_swat_helmet/ene_acc_city_swat_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_city_swat_hat/ene_acc_city_swat_hat", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_city_heavy_helmet/ene_acc_city_heavy_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_swat_heavy_visor/ene_acc_swat_heavy_visor", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_medic_helmet/ene_acc_medic_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_tazer_helmet/ene_acc_tazer_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_shield_small/ene_acc_shield_small", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_shield_lights/ene_acc_shield_lights", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_shield_city/ene_acc_shield_city", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_acc_shield_city/ene_acc_shield_city_dummy", load_husk = false },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_security_1/ene_murkywater_security_1", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_security_2/ene_murkywater_security_2", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_security_3/ene_murkywater_security_3", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_cop_1/ene_murkywater_cop_1", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_cop_2/ene_murkywater_cop_2", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_cop_3/ene_murkywater_cop_3", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_cop_4/ene_murkywater_cop_4", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_agent_1/ene_murkywater_agent_1", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_agent_2/ene_murkywater_agent_2", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_agent_3/ene_murkywater_agent_3", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_light_mp5/ene_murkywater_light_mp5", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_sniper/ene_murkywater_sniper", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_light_fbi_mp5/ene_murkywater_light_fbi_mp5", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_sniper_fbi/ene_murkywater_sniper_fbi", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_shield_fbi/ene_murkywater_shield_fbi", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_light_city_mp5/ene_murkywater_light_city_mp5", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_sniper_city/ene_murkywater_sniper_city", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_sniper_city/ene_murkywater_sniper_city", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_heavy_fbi/ene_murkywater_heavy_fbi", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_heavy_fbi_r870/ene_murkywater_heavy_fbi_r870", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_heavy_city/ene_murkywater_heavy_city", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_heavy_city_r870/ene_murkywater_heavy_city_r870", load_husk = true },
			{ path = "units/pd2_dlc_bph/characters/ene_murkywater_tazer_r870/ene_murkywater_tazer_r870", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_bex/characters/ene_swat_policia_federale/ene_swat_policia_federale",
		units_to_load = {
			{ path = "units/pd2_dlc_bex/characters/ene_acc_shield_small/ene_acc_shield_small", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_shield_city/ene_acc_shield_city", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_shield_city/ene_acc_shield_city_dummy", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_cop_cap/ene_acc_cop_cap", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_fbi_cap/ene_acc_fbi_cap", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_policia_federale_hat/ene_acc_policia_federale_hat", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_policia_federale_fbi_helmet/ene_acc_policia_federale_fbi_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_policia_federale_city_helmet/ene_acc_policia_federale_city_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_policia_federale_city_hat/ene_acc_policia_federale_city_hat", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_swat_heavy_policia_federale_helmet/ene_acc_swat_heavy_policia_federale_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_swat_heavy_policia_federale_mask/ene_acc_swat_heavy_policia_federale_mask", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_swat_heavy_policia_federale_city_helmet/ene_acc_swat_heavy_policia_federale_city_helmet", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_acc_tazer_policia_federale_mask/ene_acc_tazer_policia_federale_mask", load_husk = false },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_01/ene_policia_01", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_02/ene_policia_02", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_03/ene_policia_03", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_04/ene_policia_04", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_agent_01/ene_policia_agent_01", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_agent_02/ene_policia_agent_02", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_policia_agent_03/ene_policia_agent_03", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_policia_federale_mp5/ene_swat_policia_federale_mp5", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_policia_federale_fbi_mp5/ene_swat_policia_federale_fbi_mp5", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_fbi/ene_swat_policia_sniper_fbi", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_policia_federale_city_mp5/ene_swat_policia_federale_city_mp5", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_city/ene_swat_policia_sniper_city", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_city/ene_swat_shield_policia_federale_city", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_city/ene_swat_heavy_policia_federale_city", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_city_r870/ene_swat_heavy_policia_federale_city_r870", load_husk = true },
			{ path = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_city_r870/ene_swat_heavy_policia_federale_city_r870", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_chas/characters/ene_male_chas_police_01/ene_male_chas_police_01",
		units_to_load = {
			{ path = "units/pd2_dlc_chas/characters/ene_male_chas_police_03/ene_male_chas_police_03", load_husk = true },
			{ path = "units/pd2_dlc_chas/characters/ene_male_chas_police_04/ene_male_chas_police_04", load_husk = true },
			{ path = "units/pd2_dlc_chas/characters/ene_male_chas_police_01_fat/ene_male_chas_police_01_fat", load_husk = true },
			{ path = "units/pd2_dlc_chas/characters/ene_male_chas_police_01_fat/ene_male_chas_police_01_fat", load_husk = true },
			{ path = "units/pd2_dlc_chas/characters/ene_male_chas_police_03_fat/ene_male_chas_police_03_fat", load_husk = true },
			{ path = "units/pd2_dlc_chas/characters/ene_male_chas_police_04_fat/ene_male_chas_police_04_fat", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_01/ene_male_ranc_ranger_01",
		units_to_load = {
			{ path = "units/pd2_dlc_ranc/characters/ene_acc_ranc_ranger_hat/ene_acc_ranc_ranger_hat", load_husk = false },
			{ path = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_03/ene_male_ranc_ranger_03", load_husk = true },
			{ path = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_04/ene_male_ranc_ranger_04", load_husk = true },
			{ path = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_01_fat/ene_male_ranc_ranger_01_fat", load_husk = true },
			{ path = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_02_fat/ene_male_ranc_ranger_02_fat", load_husk = true },
			{ path = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_03_fat/ene_male_ranc_ranger_03_fat", load_husk = true },
			{ path = "units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_04_fat/ene_male_ranc_ranger_04_fat", load_husk = true },
		},
	},
	{
		unit_included = "units/pd2_dlc_usm2/characters/ene_male_marshal_shield_1/ene_male_marshal_shield_1",
		units_to_load = {
			{ path = "units/pd2_dlc_usm2/characters/ene_acc_marshal_shield_helmet/ene_acc_marshal_shield_helmet", load_husk = false },
			{ path = "units/pd2_dlc_usm2/characters/ene_acc_marshal_shield_helmet_2/ene_acc_marshal_shield_helmet_2", load_husk = false },
		},
	},
}

return M
