---@module Faction Mapping
local M = {
	["america"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["russia"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["zombie"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["murkywater"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["federales"] = {
		["CS"] = {
			swat_1 = {
				"units/pd2_dlc_bex/characters/ene_swat_policia_federale/ene_swat_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_policia_federale_mp5/ene_swat_policia_federale_mp5",
			},
			swat_2 = "units/pd2_dlc_bex/characters/ene_swat_policia_federale_r870/ene_swat_policia_federale_r870",
			heavy_1 = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale/ene_swat_heavy_policia_federale",
			heavy_2 = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_r870/ene_swat_heavy_policia_federale_r870",
			sniper = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper/ene_swat_policia_sniper",
			elite_sniper = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_city/ene_swat_policia_sniper_city",
			shield = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_c45/ene_swat_shield_policia_federale_c45",
			elite_shield = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_city/ene_swat_shield_policia_federale_city",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale/ene_swat_medic_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale/ene_swat_medic_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale_r870/ene_swat_medic_policia_federale_r870",
			},
			taser = {
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale/ene_swat_tazer_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale/ene_swat_tazer_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale_r870/ene_swat_tazer_policia_federale_r870",
			},
			cloaker = "units/pd2_dlc_bex/characters/ene_swat_cloaker_policia_federale/ene_swat_cloaker_policia_federale",
		},
		["FBI"] = {
			swat_1 = {
				"units/pd2_dlc_bex/characters/ene_swat_policia_federale_fbi/ene_swat_policia_federale_fbi",
				"units/pd2_dlc_bex/characters/ene_swat_policia_federale_fbi_mp5/ene_swat_policia_federale_fbi_mp5",
			},
			swat_2 = "units/pd2_dlc_bex/characters/ene_swat_policia_federale_fbi_r870/ene_swat_policia_federale_fbi_r870",
			heavy_1 = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_fbi/ene_swat_heavy_policia_federale_fbi",
			heavy_2 = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_fbi_r870/ene_swat_heavy_policia_federale_fbi_r870",
			sniper = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_fbi/ene_swat_policia_sniper_fbi",
			elite_sniper = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_city/ene_swat_policia_sniper_city",
			shield = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_mp9/ene_swat_shield_policia_federale_mp9",
			elite_shield = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_city/ene_swat_shield_policia_federale_city",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale/ene_swat_medic_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale/ene_swat_medic_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale_r870/ene_swat_medic_policia_federale_r870",
			},
			taser = {
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale/ene_swat_tazer_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale/ene_swat_tazer_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale_r870/ene_swat_tazer_policia_federale_r870",
			},
			cloaker = "units/pd2_dlc_bex/characters/ene_swat_cloaker_policia_federale/ene_swat_cloaker_policia_federale",
		},
		["Elite"] = {
			swat_1 = {
				"units/pd2_dlc_bex/characters/ene_swat_policia_federale_city/ene_swat_policia_federale_city",
				"units/pd2_dlc_bex/characters/ene_swat_policia_federale_city_mp5/ene_swat_policia_federale_city_mp5",
			},
			swat_2 = "units/pd2_dlc_bex/characters/ene_swat_policia_federale_city_r870/ene_swat_policia_federale_city_r870",
			heavy_1 = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_fbi/ene_swat_heavy_policia_federale_fbi",
			heavy_2 = "units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_fbi_r870/ene_swat_heavy_policia_federale_fbi_r870",
			sniper = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_fbi/ene_swat_policia_sniper_fbi",
			elite_sniper = "units/pd2_dlc_bex/characters/ene_swat_policia_sniper_city/ene_swat_policia_sniper_city",
			shield = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_mp9/ene_swat_shield_policia_federale_mp9",
			elite_shield = "units/pd2_dlc_bex/characters/ene_swat_shield_policia_federale_city/ene_swat_shield_policia_federale_city",
			bulldozer_1 = "units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1",
			bulldozer_2 = "units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2",
			elite_bulldozer_1 = "units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3",
			elite_bulldozer_2 = "units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic",
			medic = {
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale/ene_swat_medic_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale/ene_swat_medic_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_medic_policia_federale_r870/ene_swat_medic_policia_federale_r870",
			},
			taser = {
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale/ene_swat_tazer_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale/ene_swat_tazer_policia_federale",
				"units/pd2_dlc_bex/characters/ene_swat_tazer_policia_federale_r870/ene_swat_tazer_policia_federale_r870",
			},
			cloaker = "units/pd2_dlc_bex/characters/ene_swat_cloaker_policia_federale/ene_swat_cloaker_policia_federale",
		},
	},
}

return M
