---@module Faction Mapping
local M = {
	["america"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["russia"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["zombie"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["murkywater"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
	["federales"] = {
		["CS"] = {
			swat_1 = {
				"units/payday2/characters/ene_swat_1/ene_swat_1",
				"units/payday2/characters/ene_swat_3/ene_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_swat_2/ene_swat_2",
			heavy_1 = "units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1",
			heavy_2 = "units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_1/ene_sniper_1",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_2/ene_shield_2",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["FBI"] = {
			swat_1 = {
				"units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1",
				"units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
		["Elite"] = {
			swat_1 = {
				"units/payday2/characters/ene_city_swat_1/ene_city_swat_1",
				"units/payday2/characters/ene_city_swat_3/ene_city_swat_3",
			},
			swat_2 = "units/payday2/characters/ene_city_swat_2/ene_city_swat_2",
			heavy_1 = "units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1",
			heavy_2 = "units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870",
			sniper = "units/payday2/characters/ene_sniper_2/ene_sniper_2",
			elite_sniper = "units/payday2/characters/ene_sniper_3/ene_sniper_3",
			shield = "units/payday2/characters/ene_shield_1/ene_shield_1",
			elite_shield = "units/payday2/characters/ene_city_shield/ene_city_shield",
			medic = {
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_m4/ene_medic_m4",
				"units/payday2/characters/ene_medic_r870/ene_medic_r870",
			},
			taser = {
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_1/ene_tazer_1",
				"units/payday2/characters/ene_tazer_r870/ene_tazer_r870",
			},
			cloaker = "units/payday2/characters/ene_spook_1/ene_spook_1",
		},
	},
}

return M
