---@module Full-Force-Onslaught Heists
local M = {
	hox_1 = true, -- hoxout day 1
	hox_2 = true, -- hoxout day 2
	hox_3 = true, -- hoxrevenge
	arm_for = true, -- train heist
	roberts = true, -- go bank (Robert Banks)
	red2 = true, -- fwb
	mad = true, -- boiling point
	framing_frame_2 = true, -- ff day2
	framing_frame_3 = true, -- ff day3
	spa = true, -- 10-10
	flat = true, -- proom
	dinner = true, -- slouse
	pbr2 = true, -- bos
	peta2 = true, -- goat2
	vit = true, -- whouse
	des = true, -- hrock
	nmh = true, -- nmercy
	crojob2 = true, -- bomb: dockyard
	crojob3 = true, -- bomb: forest
	election_day_3 = true, -- electday 3
	election_day_3_skip1 = true, -- ditto
	election_day_3_skip2 = true, -- ditto
	watchdogs_1 = true, -- watchthedog day 1
	watchdogs_1_night = true, -- ditto
	shoutout_raid = true, -- meltdown
	jolly = true, -- Aftershock
	friend = true, -- scarmansion
	run = true, -- hstreet
	sah = true, -- shacklethrone auction
	born = true, -- bikeheist day 1
	bph = true, -- hisland
	big = true, -- bigbank
	wwh = true, -- kolyaskindeal
	mex = true, -- bordercross
	bex = true, -- sanmartini
	pex = true, -- bijuana
	pent = true, -- mmaster
	kenaz = true, -- ggc
	firestarter_2 = true, -- fs day 2
	firestarter_3 = true, -- fs day 3
	rvd1 = true, -- resdogs1
	man = true, -- ucovr
	glace = true, -- gridge
	mus = true, -- de diamond
	brb = true, -- brook bank
}

return M
