---@module Unit Sequences
local sequences = {
	security_seq_nf = { name = { "security_head_base_var1", "security_head_base_var2" }, disabled = { "face" } },
	security_seq_nh = { name = { "security_head_base_var1", "security_head_base_var2" }, disabled = { "head" } },
	swat_seq_naf = { name = { "swat_head_base_var1", "swat_head_base_var2" }, disabled = { "arms", "face" } },
	swat_seq_nah = { name = { "swat_head_base_var1", "swat_head_base_var2" }, disabled = { "arms", "head" } },
}

local M = {
	["units/payday2/characters/ene_security_1/ene_security_1"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_2/ene_security_2"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_3/ene_security_3"] = sequences.security_seq_nf,
	["units/pd2_dlc_short/characters/ene_security_1_undominatable/ene_security_1_undominatable"] = sequences.security_seq_nf,
	["units/pd2_dlc_short/characters/ene_security_2_undominatable/ene_security_2_undominatable"] = sequences.security_seq_nf,
	["units/pd2_dlc_short/characters/ene_security_3_undominatable/ene_security_3_undominatable"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_4/ene_security_4"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_5/ene_security_5"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_6/ene_security_6"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_7/ene_security_7"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_cop_1/ene_cop_1"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_cop_2/ene_cop_2"] = sequences.security_seq_nf,
	["units/pd2_dlc_short/characters/ene_cop_2_shr/ene_cop_2_shr"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_cop_3/ene_cop_3"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_cop_4/ene_cop_4"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_fbi_1/ene_fbi_1"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_fbi_2/ene_fbi_2"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_fbi_3/ene_fbi_3"] = sequences.security_seq_nh,
	["units/payday2/characters/ene_security_gensec_1/ene_security_gensec_1"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_security_gensec_2/ene_security_gensec_2"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_secret_service_1/ene_secret_service_1"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_secret_service_2/ene_secret_service_2"] = sequences.security_seq_nf,
	["units/pd2_dlc_short/characters/ene_secret_service_1_undominatable/ene_secret_service_1_undominatable"] = sequences.security_seq_nf,
	["units/pd2_dlc_casino/characters/ene_secret_service_1_casino/ene_secret_service_1_casino"] = sequences.security_seq_nf,
	["units/payday2/characters/ene_murkywater_1/ene_murkywater_1"] = sequences.swat_seq_naf,
	["units/payday2/characters/ene_murkywater_2/ene_murkywater_2"] = sequences.swat_seq_naf,
	["units/pd2_dlc_berry/characters/ene_murkywater_no_light/ene_murkywater_no_light"] = sequences.swat_seq_naf,
	["units/pd2_dlc_des/characters/ene_murkywater_no_light_not_security/ene_murkywater_no_light_not_security"] = sequences.swat_seq_naf,
	["units/pd2_dlc_des/characters/ene_murkywater_not_security_1/ene_murkywater_not_security_1"] = sequences.swat_seq_naf,
	["units/pd2_dlc_des/characters/ene_murkywater_not_security_2/ene_murkywater_not_security_2"] = sequences.swat_seq_naf,
	["units/payday2/characters/ene_swat_1/ene_swat_1"] = sequences.swat_seq_naf,
	["units/payday2/characters/ene_swat_2/ene_swat_2"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_swat_3/ene_swat_3"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_sniper_1/ene_sniper_1"] = sequences.swat_seq_naf,
	["units/payday2/characters/ene_shield_2/ene_shield_2"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1"] = sequences.swat_seq_naf,
	["units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_sniper_2/ene_sniper_2"] = sequences.swat_seq_naf,
	["units/payday2/characters/ene_shield_1/ene_shield_1"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_spook_1/ene_spook_1"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_city_swat_1/ene_city_swat_1"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_city_swat_2/ene_city_swat_2"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_city_swat_r870/ene_city_swat_r870"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_city_swat_3/ene_city_swat_3"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_sniper_3/ene_sniper_3"] = sequences.swat_seq_nah,
	["units/payday2/characters/ene_city_shield/ene_city_shield"] = sequences.swat_seq_nah,
}

return M
