return table.list_to_set({
	"Assault Tweaks Standalone Lite",
	"Assault Tweaks Standalone",
	"Full Speed Swarm",
	"Ire and Fist",
	"LIES",
	"Mildly Alarming Enemy Spawngroups",
	"Original Enemy AI",
	"Reworked Enemy AI",
	"Snap's Spawngroups",
	"United Offensive",
	"Update Special Enemies More Often",
	"Streamlined Heisting",
	"Streamlined Heisting Complements",
	"Restoration Mod",
	"Crackdown",
	"Hyper Heisting",
	"Skill Overhaul",
	"No Leech",
    "Hinaomi's Rebalance - Weapons",
    "Hinaomi's Rebalance - Skills & Perk Decks",
    "Hinaomi's Rebalance - Weapon Conversion Kits",
    "Better Bots",
	"Melee Overhaul ME: Melee Sprinting",
	"Melee Overhaul ME: Sprint Hold",
	"Melee Overhaul ME: Melee Decapitations",
	"Graceful Graze",
	"Better Graze",
	"Graze doesn't kill civis",
	"Graze Plus - Make graze effect apply of opposite side",
	"Enemy Accuracy Fix",
	"Better Cops weapon usage and some tweaks",
	"Better Cops weapon usage",
	"Better Cops weapon usage and some tweaks for online",
	"Better Cops weapon usage for online"
})
