-- For Network Hook IDs, the naming convention is as follows:
-- 1. Prefix with Eclipse_
-- 2. Follow with the class name that sends the network string
-- 3. Follow with the method in the class that sends the string
-- 4. In case a single method sends multiple strings, prefix
-- all following strings with an index
--
-- e.g. If you're sending a string from PlayerManager using
-- the function [PlayerManager.do_stuff(...)]
-- then the corresponding ID is "Eclipse_PlayerManager.do_stuff"
-- and if there is another request to send, the corresponding ID
-- would be "Eclipse_PlayerManager.do_stuff2"
