return {
	[("units/payday2/characters/ene_cop_3/ene_cop_3"):key()] = "r870",
	[("units/payday2/characters/ene_cop_4/ene_cop_4"):key()] = "mp5",
	[("units/pd2_dlc_rvd/characters/ene_la_cop_3/ene_la_cop_3"):key()] = "r870",
	[("units/pd2_dlc_rvd/characters/ene_la_cop_4/ene_la_cop_4"):key()] = "mp5",
	[("units/pd2_dlc_chas/characters/ene_male_chas_police_01/ene_male_chas_police_01"):key()] = { "c45", "raging_bull" },
	[("units/pd2_dlc_chas/characters/ene_male_chas_police_02/ene_male_chas_police_02"):key()] = { "mp5", "r870" },
	[("units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_01/ene_male_ranc_ranger_01"):key()] = { "c45", "raging_bull" },
	[("units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_02/ene_male_ranc_ranger_02"):key()] = { "mp5", "r870" },
	[("units/payday2/characters/ene_fbi_1/ene_fbi_1"):key()] = "mp5",
	[("units/payday2/characters/ene_fbi_3/ene_fbi_3"):key()] = "r870",
	[("units/payday2/characters/ene_medic_m4/ene_medic_m4"):key()] = "mp5",
	[("units/payday2/characters/ene_spook_1/ene_spook_1"):key()] = "beretta92",
	[("units/payday2/characters/ene_biker_3/ene_biker_3"):key()] = "mossberg",
	[("units/pd2_dlc_born/characters/ene_biker_female_3/ene_biker_female_3"):key()] = "mossberg",
	[("units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1"):key()] = "r870_tank",
	[("units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2"):key()] = "aa12_tank",
	[("units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3"):key()] = "m249_tank",
	[("units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic"):key()] = "benelli_tank",
	[("units/pd2_dlc_drm/characters/ene_bulldozer_minigun/ene_bulldozer_minigun"):key()] = "benelli_tank",
}
