local head_sequences = {
	security = {
		material = { 1, 2 },
		run_sequence = {
			"security_head_init",
			"disable_face",
		},
	},
	security_fat = {
		material = { 1, 2 },
		run_sequence = {
			"security_fat_head_init",
			"disable_face",
		},
	},
	hrt = {
		material = { 1, 2 },
		run_sequence = {
			"security_head_init",
			"disable_head",
		},
	},
	soldier_a = {
		material = 2,
		run_sequence = {
			"soldier_head_init",
		},
	},
	soldier_b = {
		material = 2,
		run_sequence = {
			"soldier_head_init",
			"disable_arms",
		},
	},
	blue_swat_a = {
		material = { 1, 2 },
		run_sequence = {
			"set_blue_swat",
			"swat_head_init",
			"random_balaclava_common",
			"disable_arms",
		},
	},
	blue_swat_b = {
		material = { 1, 2 },
		run_sequence = {
			"set_blue_swat",
			"swat_head_init",
			"random_balaclava_rare",
			"disable_arms",
		},
	},
	blue_swat_c = {
		material = { 1, 2 },
		run_sequence = {
			"set_blue_swat",
			"swat_head_init",
			"disable_head",
			"disable_arms",
		},
	},
	fbi_swat_a = {
		material = { 1, 2 },
		run_sequence = {
			"swat_head_init",
			"random_balaclava_common",
			"disable_arms",
		},
	},
	fbi_swat_b = {
		material = { 1, 2 },
		run_sequence = {
			"swat_head_init",
			"random_balaclava_rare",
			"disable_arms",
		},
	},
	fbi_swat_c = {
		material = { 1, 2 },
		run_sequence = {
			"swat_head_init",
			"disable_head",
			"disable_arms",
		},
	},
	city_swat_a = {
		material = { 1, 2 },
		run_sequence = {
			"elite_swat_head_init",
			"random_balaclava_common",
			"disable_arms",
		},
	},
	city_swat_b = {
		material = { 1, 2 },
		run_sequence = {
			"elite_swat_head_init",
			"random_balaclava_rare",
			"disable_arms",
		},
	},
	city_swat_c = {
		material = { 1, 2 },
		run_sequence = {
			"elite_swat_head_init",
			"disable_head",
			"disable_arms",
		},
	},
	bulldozer = {
		material = { 1, 2 },
		run_sequence = {
			"bulldozer_head_init",
			"disable_head",
			"disable_arms",
		},
	},
	medic = {
		material = { 1, 2 },
		run_sequence = {
			"set_medic",
			"swat_head_init",
			"random_balaclava_common",
			"disable_arms",
		},
	},
}
---@module Unit Sequences
local M = {
	["units/payday2/characters/ene_security_1/ene_security_1"] = { name = "security_1", head = head_sequences.security },
	["units/payday2/characters/ene_security_2/ene_security_2"] = { name = "security_2", head = head_sequences.security },
	["units/payday2/characters/ene_security_3/ene_security_3"] = { name = "security_3", head = head_sequences.security },
	["units/payday2/characters/ene_security_1_fat/ene_security_1_fat"] = { name = "security_1_fat", head = head_sequences.security_fat },
	["units/payday2/characters/ene_security_2_fat/ene_security_2_fat"] = { name = "security_2_fat", head = head_sequences.security_fat },
	["units/payday2/characters/ene_security_3_fat/ene_security_3_fat"] = { name = "security_3_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_short/characters/ene_security_1_undominatable/ene_security_1_undominatable"] = { name = "security_1", head = head_sequences.security },
	["units/pd2_dlc_short/characters/ene_security_2_undominatable/ene_security_2_undominatable"] = { name = "security_2", head = head_sequences.security },
	["units/pd2_dlc_short/characters/ene_security_3_undominatable/ene_security_3_undominatable"] = { name = "security_3", head = head_sequences.security },
	["units/payday2/characters/ene_security_4/ene_security_4"] = { name = "security_4", head = head_sequences.security },
	["units/payday2/characters/ene_security_5/ene_security_5"] = { name = "security_5", head = head_sequences.security },
	["units/payday2/characters/ene_security_6/ene_security_6"] = { name = "security_6", head = head_sequences.security },
	["units/payday2/characters/ene_security_7/ene_security_7"] = { name = "security_7", head = head_sequences.security },
	["units/payday2/characters/ene_security_8/ene_security_8"] = { name = "security_8", head = head_sequences.security },
	["units/payday2/characters/ene_cop_1/ene_cop_1"] = { name = "cop_1", head = head_sequences.security },
	["units/payday2/characters/ene_cop_2/ene_cop_2"] = { name = "cop_2", head = head_sequences.security },
	["units/pd2_dlc_short/characters/ene_cop_2_shr/ene_cop_2_shr"] = { name = "cop_2", head = head_sequences.security },
	["units/payday2/characters/ene_cop_3/ene_cop_3"] = { name = "cop_3", head = head_sequences.security },
	["units/payday2/characters/ene_cop_4/ene_cop_4"] = { name = "cop_4", head = head_sequences.security },
	["units/payday2/characters/ene_cop_1_fat/ene_cop_1_fat"] = { name = "cop_1_fat", head = head_sequences.security_fat },
	["units/payday2/characters/ene_cop_2_fat/ene_cop_2_fat"] = { name = "cop_2_fat", head = head_sequences.security_fat },
	["units/payday2/characters/ene_cop_3_fat/ene_cop_3_fat"] = { name = "cop_3_fat", head = head_sequences.security_fat },
	["units/payday2/characters/ene_cop_4_fat/ene_cop_4_fat"] = { name = "cop_4_fat", head = head_sequences.security_fat },
	["units/payday2/characters/ene_fbi_1/ene_fbi_1"] = { name = "fbi_1", head = head_sequences.security },
	["units/payday2/characters/ene_fbi_2/ene_fbi_2"] = { name = "fbi_2", head = head_sequences.security },
	["units/payday2/characters/ene_fbi_3/ene_fbi_3"] = { name = "fbi_3", head = head_sequences.hrt },
	["units/pd2_dlc1/characters/ene_security_gensec_1/ene_security_gensec_1"] = { name = "gensec_1", head = head_sequences.security },
	["units/pd2_dlc1/characters/ene_security_gensec_2/ene_security_gensec_2"] = { name = "gensec_2", head = head_sequences.security },
	["units/payday2/characters/ene_secret_service_1/ene_secret_service_1"] = { name = "secret_service_1", head = head_sequences.security },
	["units/payday2/characters/ene_secret_service_2/ene_secret_service_2"] = { name = "secret_service_1", head = head_sequences.security },
	["units/pd2_dlc_short/characters/ene_secret_service_1_undominatable/ene_secret_service_1_undominatable"] = { name = "secret_service_1", head = head_sequences.security },
	["units/pd2_dlc_casino/characters/ene_secret_service_1_casino/ene_secret_service_1_casino"] = { name = "secret_service_2", head = head_sequences.security },
	["units/payday2/characters/ene_murkywater_1/ene_murkywater_1"] = { name = "murkywater_1", head = head_sequences.blue_swat_b },
	["units/payday2/characters/ene_murkywater_2/ene_murkywater_2"] = { name = "murkywater_1", head = head_sequences.blue_swat_b },
	["units/pd2_dlc_berry/characters/ene_murkywater_no_light/ene_murkywater_no_light"] = { name = "murkywater_1", head = head_sequences.blue_swat_b },
	["units/pd2_dlc_des/characters/ene_murkywater_no_light_not_security/ene_murkywater_no_light_not_security"] = { name = "murkywater_1", head = head_sequences.blue_swat_b },
	["units/pd2_dlc_des/characters/ene_murkywater_not_security_1/ene_murkywater_not_security_1"] = { name = "murkywater_1", head = head_sequences.blue_swat_b },
	["units/pd2_dlc_des/characters/ene_murkywater_not_security_2/ene_murkywater_not_security_2"] = { name = "murkywater_1", head = head_sequences.blue_swat_b },
	["units/payday2/characters/ene_swat_1/ene_swat_1"] = { name = "swat_1", head = head_sequences.blue_swat_b },
	["units/payday2/characters/ene_swat_2/ene_swat_2"] = { name = "swat_2", head = head_sequences.blue_swat_a },
	["units/payday2/characters/ene_swat_3/ene_swat_3"] = { name = "swat_3", head = head_sequences.blue_swat_a },
	["units/payday2/characters/ene_swat_heavy_1/ene_swat_heavy_1"] = { name = "heavy_1", head = head_sequences.blue_swat_a },
	["units/payday2/characters/ene_swat_heavy_r870/ene_swat_heavy_r870"] = { name = "heavy_2", head = head_sequences.blue_swat_a },
	["units/payday2/characters/ene_shield_2/ene_shield_2"] = { name = "shield_2", head = head_sequences.blue_swat_c },
	["units/payday2/characters/ene_sniper_1/ene_sniper_1"] = { name = "sniper_1", head = head_sequences.blue_swat_b },
	["units/payday2/characters/ene_tazer_1/ene_tazer_1"] = { name = "taser_1", head = head_sequences.blue_swat_b },
	["units/payday2/characters/ene_tazer_r870/ene_tazer_r870"] = { name = "taser_2", head = head_sequences.blue_swat_c },
	["units/payday2/characters/ene_fbi_swat_1/ene_fbi_swat_1"] = { name = "fbi_swat_1", head = head_sequences.fbi_swat_b },
	["units/payday2/characters/ene_fbi_swat_2/ene_fbi_swat_2"] = { name = "fbi_swat_2", head = head_sequences.fbi_swat_a },
	["units/payday2/characters/ene_fbi_swat_3/ene_fbi_swat_3"] = { name = "fbi_swat_3", head = head_sequences.fbi_swat_a },
	["units/payday2/characters/ene_sniper_2/ene_sniper_2"] = { name = "sniper_2", head = head_sequences.fbi_swat_b },
	["units/payday2/characters/ene_shield_1/ene_shield_1"] = { name = "shield_1", head = head_sequences.fbi_swat_c },
	["units/payday2/characters/ene_fbi_heavy_1/ene_fbi_heavy_1"] = { name = "fbi_heavy_1", head = head_sequences.fbi_swat_c },
	["units/payday2/characters/ene_fbi_heavy_r870/ene_fbi_heavy_r870"] = { name = "fbi_heavy_2", head = head_sequences.fbi_swat_c },
	["units/payday2/characters/ene_medic_m4/ene_medic_m4"] = { name = "medic_1", head = head_sequences.medic },
	["units/payday2/characters/ene_medic_r870/ene_medic_r870"] = { name = "medic_2", head = head_sequences.medic },
	["units/payday2/characters/ene_spook_1/ene_spook_1"] = { name = "cloaker_1", head = head_sequences.fbi_swat_c },
	["units/payday2/characters/ene_city_swat_1/ene_city_swat_1"] = { name = "city_swat_1", head = head_sequences.city_swat_a },
	["units/payday2/characters/ene_city_swat_2/ene_city_swat_2"] = { name = "city_swat_2", head = head_sequences.city_swat_a },
	["units/payday2/characters/ene_city_swat_r870/ene_city_swat_r870"] = { name = "city_swat_2", head = head_sequences.city_swat_a },
	["units/payday2/characters/ene_city_swat_3/ene_city_swat_3"] = { name = "city_swat_3", head = head_sequences.city_swat_a },
	["units/payday2/characters/ene_sniper_3/ene_sniper_3"] = { name = "sniper_3", head = head_sequences.city_swat_a },
	["units/payday2/characters/ene_city_shield/ene_city_shield"] = { name = "shield_3", head = head_sequences.city_swat_c },
	["units/payday2/characters/ene_bulldozer_1/ene_bulldozer_1"] = { name = "bulldozer_1", head = head_sequences.bulldozer },
	["units/payday2/characters/ene_bulldozer_2/ene_bulldozer_2"] = { name = "bulldozer_2", head = head_sequences.bulldozer },
	["units/payday2/characters/ene_bulldozer_3/ene_bulldozer_3"] = { name = "bulldozer_3", head = head_sequences.bulldozer },
	["units/pd2_dlc_drm/characters/ene_bulldozer_minigun_classic/ene_bulldozer_minigun_classic"] = { name = "bulldozer_mini", head = head_sequences.bulldozer },
	["units/pd2_mcmansion/characters/ene_hoxton_breakout_guard_1/ene_hoxton_breakout_guard_1"] = { name = "mcmansion_security_1", head = head_sequences.blue_swat_b },
	["units/pd2_mcmansion/characters/ene_hoxton_breakout_guard_2/ene_hoxton_breakout_guard_2"] = { name = "mcmansion_security_1", head = head_sequences.blue_swat_b },
	["units/pd2_dlc_army/characters/ene_soldier_1/ene_soldier_1"] = { name = "soldier_1", head = head_sequences.soldier_a },
	["units/pd2_dlc_army/characters/ene_soldier_2/ene_soldier_2"] = { name = "soldier_2", head = head_sequences.soldier_b },
	["units/pd2_dlc_army/characters/ene_soldier_3/ene_soldier_3"] = { name = "soldier_3", head = head_sequences.soldier_b },
	["units/pd2_dlc_rvd/characters/ene_la_cop_1/ene_la_cop_1"] = { name = "la_cop_1", head = head_sequences.security },
	["units/pd2_dlc_rvd/characters/ene_la_cop_2/ene_la_cop_2"] = { name = "la_cop_2", head = head_sequences.security },
	["units/pd2_dlc_rvd/characters/ene_la_cop_3/ene_la_cop_3"] = { name = "la_cop_3", head = head_sequences.security },
	["units/pd2_dlc_rvd/characters/ene_la_cop_4/ene_la_cop_4"] = { name = "la_cop_4", head = head_sequences.security },
	["units/pd2_dlc_rvd/characters/ene_la_cop_1_fat/ene_la_cop_1_fat"] = { name = "la_cop_1_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_rvd/characters/ene_la_cop_2_fat/ene_la_cop_2_fat"] = { name = "la_cop_2_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_rvd/characters/ene_la_cop_3_fat/ene_la_cop_3_fat"] = { name = "la_cop_3_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_rvd/characters/ene_la_cop_4_fat/ene_la_cop_4_fat"] = { name = "la_cop_4_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_01/ene_male_chas_police_01"] = { name = "chas_police_1", head = head_sequences.security },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_02/ene_male_chas_police_02"] = { name = "chas_police_2", head = head_sequences.security },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_03/ene_male_chas_police_03"] = { name = "chas_police_3", head = head_sequences.security },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_04/ene_male_chas_police_04"] = { name = "chas_police_4", head = head_sequences.security },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_01_fat/ene_male_chas_police_01_fat"] = { name = "chas_police_1_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_02_fat/ene_male_chas_police_02_fat"] = { name = "chas_police_2_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_03_fat/ene_male_chas_police_03_fat"] = { name = "chas_police_3_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_chas/characters/ene_male_chas_police_04_fat/ene_male_chas_police_04_fat"] = { name = "chas_police_4_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_01/ene_male_ranc_ranger_01"] = { name = "ranc_ranger_1", head = head_sequences.security },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_02/ene_male_ranc_ranger_02"] = { name = "ranc_ranger_2", head = head_sequences.security },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_03/ene_male_ranc_ranger_03"] = { name = "ranc_ranger_3", head = head_sequences.security },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_04/ene_male_ranc_ranger_04"] = { name = "ranc_ranger_4", head = head_sequences.security },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_01_fat/ene_male_ranc_ranger_01_fat"] = { name = "ranc_ranger_1_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_02_fat/ene_male_ranc_ranger_02_fat"] = { name = "ranc_ranger_2_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_03_fat/ene_male_ranc_ranger_03_fat"] = { name = "ranc_ranger_3_fat", head = head_sequences.security_fat },
	["units/pd2_dlc_ranc/characters/ene_male_ranc_ranger_04_fat/ene_male_ranc_ranger_04_fat"] = { name = "ranc_ranger_4_fat", head = head_sequences.security_fat },
}

return M
