---@module Unit Material Variants
local M = {
	"units/payday2/characters/ene_acc_head/vars/ene_acc_head_var1",
	"units/payday2/characters/ene_acc_head/vars/ene_acc_head_var2",
	"units/payday2/characters/ene_acc_head_female/ene_acc_head_female",
	"units/payday2/characters/ene_cop_1/vars/ene_security_1",
	"units/payday2/characters/ene_cop_1/vars/ene_security_4",
	"units/payday2/characters/ene_cop_1/vars/ene_fbi_1",
	"units/payday2/characters/ene_cop_1/vars/ene_prisonguard_male_1",
	"units/payday2/characters/ene_cop_1/vars/ene_la_cop_1",
	"units/payday2/characters/ene_cop_1/vars/ene_bex_security_01",
	"units/payday2/characters/ene_cop_1/vars/ene_policia_01",
	"units/payday2/characters/ene_cop_1/vars/ene_policia_agent_01",
	"units/payday2/characters/ene_cop_1/vars/ene_male_office_cop_01",
	"units/payday2/characters/ene_secret_service_1/vars/ene_secret_service_1_casino",
	"units/payday2/characters/ene_secret_service_1/vars/ene_bex_security_suit_01",
	"units/payday2/characters/ene_murkywater_1/vars/ene_hoxton_breakout_guard_1",
	"units/payday2/characters/ene_swat_1/vars/ene_fbi_swat_1",
	"units/payday2/characters/ene_swat_1/vars/ene_city_swat_1",
	"units/payday2/characters/ene_fbi_heavy_1/vars/ene_city_heavy_g36",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_bulldozer_2",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_bulldozer_3",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_bulldozer_4",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_bulldozer_minigun_classic",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_bulldozer_medic_classic",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_snowman_boss",
	"units/payday2/characters/ene_bulldozer_1/vars/ene_dozer_piggy",
	"units/pd2_dlc_chas/characters/ene_male_chas_police_01/vars/ene_male_ranc_ranger_01",
	"units/pd2_dlc_usm1/characters/ene_male_marshal_marksman_1/vars/ene_male_marshal_marksman_1_merc",
	"units/pd2_dlc_bex/characters/ene_acc_mexican_head/vars/ene_acc_mexican_head_var1",
	"units/pd2_dlc_bex/characters/ene_acc_mexican_head/vars/ene_acc_mexican_head_var2",
	"units/pd2_dlc_bex/characters/ene_swat_policia_federale/vars/ene_swat_policia_federale_fbi",
	"units/pd2_dlc_bex/characters/ene_swat_policia_federale/vars/ene_swat_policia_federale_city",
	"units/pd2_dlc_bex/characters/ene_swat_heavy_policia_federale_fbi/vars/ene_swat_heavy_policia_federale_city",
	"units/pd2_dlc_army/characters/ene_acc_soldier_head/vars/ene_acc_soldier_head_var1",
	"units/pd2_dlc_army/characters/ene_acc_soldier_head/vars/ene_acc_soldier_head_var2",
}

return M
